### ISSUE TITLE
Plantilla csv

### ISSUE THREAD

**Issue by oscarss24** [benoithubert/wp-pro-quiz-csv#1]
Hello !, I do not speak English . so apologies for the translation .. first of all congratulations on creating the possibility of importing from csv , but unfortunately I can not do it , I get the error attached , you can send me a csv file template in excel to get it done the correct import ? thank you very much !
--------------------------------------------------
Hola!, no hablo ingles. asi que disculpas por la traducción.. ante todo enhorabuena por crear la posibilidad de importar desde csv, pero por desgracia no consigo hacerlo, me da el error que adjunto, me puedes enviar un fichero csv de plantilla en excel para conseguir que se haga la importacion correcta? muchas gracias!
![error](https://cloud.githubusercontent.com/assets/11404003/6571256/816d16a6-c706-11e4-99a2-17726a8ba8e3.jpg)

**Comment by benoithubert** [comment]
This follows our talk over email today. Just so that others have the information as well, and to mark the issue as closed.

Sample CSV:

    Quiz name
    A sample quiz,This is the quiz description.
    What's the capital of the United States?,single,New York|Los Angeles|Washington D.C.,Washington D.C.
    Which band sang Hey Jude?,single,The Beatles|The Rolling Stones|AC/DC,The Beatles
    Which of those mountain ranges have a part of them in France?,multiple,The Alps|The Rocky Mountains|The Pyrenees|The Himalayas,The Alps|The Pyrenees
